version: '3'
services:
  server:
    container_name: okiniarts_server
    build: ./server
    command: /server
    volumes:
      - ./server:/go/src/github.com/y-yagi/okiniarts
      - /go/src/github.com/y-yagi/okiniarts/vendor
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://okiniarts:okiniarts@db/okiniarts?sslmode=disable
  client:
    container_name: okiniarts_client
    build: ./client
    command: npm start
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
  db:
    container_name: okiniarts_db
    build: ./db
    ports:
      - "5434:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql:
    driver: local
  client:
    driver: local
  server:
    driver: local
