version: 2.1

orbs:
  cypress: cypress-io/cypress@1

jobs:
  unit-test:
    docker:
      - image: circleci/golang:1.12-node-browsers
        environment:
          GO111MODULE: "on"
      - image: circleci/postgres:10-alpine
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: okiniarts_test

    working_directory: /go/src/github.com/y-yagi/okiniarts/

    steps:
      - checkout

      - run:
          name: Run go mod
          command: |
            cd server
            go mod download
            go mod vendor

      - run:
          name: Run lint
          command: |
            cd server
            go get -u golang.org/x/lint/golint
            golint -set_exit_status

      - run:
          name: Run staticcheck
          command: |
            cd server
            go get honnef.co/go/tools/cmd/staticcheck
            GO111MODULE=off staticcheck

      - run:
          name: Installing Dependencies
          command: |
            sudo apt-get install postgresql-client

      - run:
          environment:
            DATABASE_URL: "postgres://ubuntu@localhost:5432/okiniarts_test?sslmode=disable"
            PUBKEY: "testdata/jwtRS256.key.pub"

          name: Run tests
          command: |
            cd server
            psql -p 5432 -h localhost -U ubuntu okiniarts_test < migrations/01_add_tables.sql
            go test -v

      - run:
          name: Build server
          command: |
            cd server
            GO111MODULE=on CGO_ENABLED=0 GOOS=linux go build -a -installsuffix nocgo -o ./okiniarts-server .
            mkdir ~/server && mv ./okiniarts-server  ~/server

      - persist_to_workspace:
          root: ~/
          paths: server

  e2e-test:
    docker:
      - image: circleci/golang:1.12-node-browsers
      - image: circleci/postgres:10-alpine
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: okiniarts_test

    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Installing locale
          command: |
            sudo apt install task-japanese
            echo 'ja_JP.UTF-8 UTF-8' | sudo tee -a  /etc/locale.gen
            sudo locale-gen
            sudo update-locale LANG=ja_JP.UTF-8

      - run:
          name: Installing Dependencies
          command: |
            sudo apt-get install postgresql-client

      - run:
          name: Create tables
          command: |
            psql -p 5432 -h localhost -U ubuntu okiniarts_test < ~/project/server/migrations/01_add_tables.sql

      - run:
          name: Import seeds
          command: |
            psql -p 5432 -h localhost -U ubuntu okiniarts_test < ~/project/client/cypress/fixtures/seeds.sql

      - run:
          environment:
            DATABASE_URL: "postgres://ubuntu@localhost:5432/okiniarts_test?sslmode=disable"

          name: Start API server
          background: true
          command: |
            cd ~/server
            echo $ENCODED_PUBKEY | base64 -d > auth0_pubkey
            ./okiniarts-server

      - run:
          name: Start client
          background: true
          command: |
            cd ~/project/client
            sed -i -e "s/server:3001/localhost:3001/g" package.json
            yarn start

      - run:
          name: Wait start client
          command: |
            sudo npm install -g wait-on
            wait-on http://localhost:3000

      - run:
          name: Run Cypress tests
          command: |
            cd ~/project/client
            yarn run cypress run

      - store_artifacts:
          path: /home/circleci/project/client/cypress/screenshots

      - store_artifacts:
          path: /home/circleci/project/client/cypress/videos


workflows:
  build:
    jobs:
      - unit-test
      - cypress/install:
          requires:
            - unit-test
          working_directory: ~/project/client
          yarn: true
      - e2e-test:
          requires:
            - cypress/install
